[tool.poetry]
name = "multimodal_research"
version = "1.0.0"
description = "MultiModal Research Project X"
authors = ["Hakim Temacini"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
